# PBS configuration
# If submitting to a different project to your default uncomment line below 
# and change project code as appropriate
project: e14
queue: normal
walltime: 4:00:00
jobname: 1deg_iaf_Full
ncpus: 252
mem: 500GB

# Force payu to always find, and save, files in this short (or scratch) project directory
# shortpath: /scratch/w35

# Model configuration
name: common
model: access-om2
input: /g/data/ik11/inputs/access-om2/input_236a3011/common_1deg_jra55
submodels:
    - name: atmosphere
      model: yatm
      exe: /g/data/ik11/inputs/access-om2/bin/yatm_4198e150.exe
      input: 
            - /g/data/ik11/inputs/access-om2/input_236a3011/yatm_1deg
            - /g/data/qv56/replicas/input4MIPs/CMIP6/OMIP/MRI/MRI-JRA55-do-1-3/atmos/3hr/rsds/gn/v20180412
            - /g/data/qv56/replicas/input4MIPs/CMIP6/OMIP/MRI/MRI-JRA55-do-1-3/atmos/3hr/rlds/gn/v20180412
            - /g/data/qv56/replicas/input4MIPs/CMIP6/OMIP/MRI/MRI-JRA55-do-1-3/atmos/3hr/prra/gn/v20180412
            - /g/data/qv56/replicas/input4MIPs/CMIP6/OMIP/MRI/MRI-JRA55-do-1-3/atmos/3hr/prsn/gn/v20180412
            - /g/data/qv56/replicas/input4MIPs/CMIP6/OMIP/MRI/MRI-JRA55-do-1-3/atmos/3hrPt/psl/gn/v20180412
            - /g/data/qv56/replicas/input4MIPs/CMIP6/OMIP/MRI/MRI-JRA55-do-1-3/ocean/day/friver/gn/v20180412
            - /g/data/qv56/replicas/input4MIPs/CMIP6/OMIP/MRI/MRI-JRA55-do-1-3/atmos/3hrPt/tas/gn/v20180412
            - /g/data/qv56/replicas/input4MIPs/CMIP6/OMIP/MRI/MRI-JRA55-do-1-3/atmos/3hrPt/huss/gn/v20180412
            - /g/data/qv56/replicas/input4MIPs/CMIP6/OMIP/MRI/MRI-JRA55-do-1-3/atmos/3hrPt/uas/gn/v20180412
            - /g/data/qv56/replicas/input4MIPs/CMIP6/OMIP/MRI/MRI-JRA55-do-1-3/atmos/3hrPt/vas/gn/v20180412
      ncpus: 1

    - name: ocean
      model: mom
#      exe: /g/data/ik11/inputs/access-om2/bin/fms_ACCESS-OM_e837d05d_libaccessom2_4198e150.x
      exe: /g/data/e14/rmh561/access-om2/bin/fms_ACCESS-OM_fd3e1a3_libaccessom2_a9d4b67.x
      input: /g/data/ik11/inputs/access-om2/input_236a3011/mom_1deg
      ncpus: 216

    - name: ice
      model: cice5
      exe: /g/data/ik11/inputs/access-om2/bin/cice_auscom_360x300_24p_597e4561_libaccessom2_4198e150.exe
      input: /g/data/ik11/inputs/access-om2/input_236a3011/cice_1deg
      ncpus: 24

# Collation
collate:
  walltime: 3:00:00
  mem: 30GB
  ncpus: 4
  queue: express
  exe: /g/data/ik11/inputs/access-om2/bin/mppnccombine

# Misc
runlog: true
stacksize: unlimited
qsub_flags: -lother=hyperthread -W umask=027 -l storage=gdata/hh5+gdata/ik11+scratch/e14+gdata/ua8+gdata/e14
# set number of cores per node (28 for normalbw, 48 for normal on gadi)
platform:
    nodesize: 48

# DANGER! Do not uncomment this without checking the script is synching 
# to the correct location!
# postscript: sync_output_to_gdata.sh
